import Head from 'next/head'
import Image from 'next/image'
import HomePanner from "../components/home/Panner"
import styles from '../styles/Home.module.css'
import Slider from '../components/home/Slider'
import ConenctionWithUs from '../components/ConenctWithUs'
import BoxCollection from '../components/home/BoxCollection'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-fit ">
         <HomePanner/>                                                                
         <BoxCollection fristCollection="best cellers" secondCollection="new Collection"/>
          <Slider title="best Sellers"/>
          <Slider title="new Collection"/>
          <BoxCollection fristCollection="best cellers" secondCollection="new Collection"/>
          <Slider title="new collection"/>
         <ConenctionWithUs/>
      </div>
    </div>
  )
}
